
// Objective-C API for talking to the following Go packages
//
//	code.1cobo.com/cobo-tss-service/sdkv2/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TSSSDK_FRAMEWORK_H__
#define __TSSSDK_FRAMEWORK_H__

#include "Tss.objc.h"
#include "Universe.objc.h"

#endif
